CREATE DATABASE `620391-yeticave`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

 CREATE TABLE `categories`(
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`name` CHAR(120) NOT NULL UNIQUE
);
 
CREATE TABLE `lots`(
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`date_add` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`title` CHAR(60) NOT NULL,
	`description` TEXT DEFAULT NULL,
	`img` path CHAR(128) NOT NULL,
	`bet` INT NOT NULL,
	`date_end` end DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 CREATE TABLE `bets`(
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`date_bet` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`bet_end` INT NOT NULL
);
 CREATE TABLE `users`(
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`name` CHAR(120) NOT NULL,
	`email` CHAR(120) NOT NULL,
	`password` CHAR (60) NOT NULL,
	`avatar` CHAR(120) NOT NULL,
	`date_reg` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`contacts` CHAR(250) NOT NULL
);
CREATE UNIQUE INDEX `name` ON categories(name);
CREATE UNIQUE INDEX `title` ON lots(title);
CREATE UNIQUE INDEX `email` ON users(email);
CREATE UNIQUE INDEX `name` ON users(name);