CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

 CREATE TABLE categories(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(30) NOT NULL UNIQUE
);
 
CREATE TABLE lots(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dtlot DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	lot title CHAR(60) NOT NULL UNIQUE,
	description TEXT DEFAULT NULL,
	img path CHAR(128) NOT NULL,
	cost INT NOT NULL,
	dt end DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 CREATE TABLE bets(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dtbet DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	end_cost INT NOT NULL
);
 CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(30) NOT NULL UNIQUE,
	email CHAR(128) NOT NULL UNIQUE,
	password CHAR (64) NOT NULL,
	avatar_path CHAR(128) NOT NULL,
	dtreg DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	contacts CHAR(250) NOT NULL
);
 CREATE UNIQUE INDEX catname ON categories(name);
CREATE UNIQUE INDEX title ON lots(lot_title);
CREATE UNIQUE INDEX mail ON users(email);
CREATE UNIQUE INDEX usrname ON users(name);
 CREATE INDEX descr ON lots(description);